// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLWKwsLY7f84wwaNGCX844uTE2rFV5rJQ',
    appId: '1:709290779438:web:b8758fdf7f8cb15a8ad0bf',
    messagingSenderId: '709290779438',
    projectId: 'gky1-105f7',
    authDomain: 'gky1-105f7.firebaseapp.com',
    storageBucket: 'gky1-105f7.appspot.com',
    measurementId: 'G-6ZBWJX359R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC1oahaKmQY8Vh0u4vul7WjN3S1DjOzFg',
    appId: '1:709290779438:android:1a33f891ec750ddc8ad0bf',
    messagingSenderId: '709290779438',
    projectId: 'gky1-105f7',
    storageBucket: 'gky1-105f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_4nOJ1OnN8P_iV5R70tq-jjOzRALIoGQ',
    appId: '1:709290779438:ios:2ceba35fa791fd718ad0bf',
    messagingSenderId: '709290779438',
    projectId: 'gky1-105f7',
    storageBucket: 'gky1-105f7.appspot.com',
    iosBundleId: 'com.example.giuaky1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_4nOJ1OnN8P_iV5R70tq-jjOzRALIoGQ',
    appId: '1:709290779438:ios:2ceba35fa791fd718ad0bf',
    messagingSenderId: '709290779438',
    projectId: 'gky1-105f7',
    storageBucket: 'gky1-105f7.appspot.com',
    iosBundleId: 'com.example.giuaky1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLWKwsLY7f84wwaNGCX844uTE2rFV5rJQ',
    appId: '1:709290779438:web:b3994549d5625c2e8ad0bf',
    messagingSenderId: '709290779438',
    projectId: 'gky1-105f7',
    authDomain: 'gky1-105f7.firebaseapp.com',
    storageBucket: 'gky1-105f7.appspot.com',
    measurementId: 'G-6MBEN5VMB8',
  );
}
